# Generated by Django 5.1.3 on 2024-11-27 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='available',
        ),
        migrations.AddField(
            model_name='device',
            name='available_times',
            field=models.JSONField(default=list),
        ),
    ]
